### ISSUE TITLE
Problem with nonlinear system in ConTest.Conflict

### ISSUE THREAD

**Issue by lochel** [AMIT-HSBI/PNlib#72]
According to the OpenModelica coverage test, there is a problem with a nonlinear system in ConTest.Conflict:
https://libraries.openmodelica.org/branches/master/PNlib/PNlib.html

The problem was not present in earlier versions of OpenModelica. However, it needs more investigation to find out if it should be fixed in the library or in OpenModelica.

**Comment by casella** [comment]
See also [#6400](https://trac.openmodelica.org/OpenModelica/ticket/6400).

**Comment by lochel** [comment]
It works fine if we add `___OpenModelica_simulationFlags(nls = "newton", s = "rungekutta")` to the example's annotation.

**Comment by phannebohm** [comment]
OpenModelica supports PNlib 100% so this is fixed I guess.
