### ISSUE TITLE
Any plan for Modelica 4.0.0?

### ISSUE THREAD

**Issue by wangzizhe** [AMIT-HSBI/PNlib#75]
Hi,

I saw from the `package.mo`:

```
within ;
package PNlib
  annotation(uses(Modelica(version="3.2.3")), version="2.2");
end PNlib;
```

Is there any plan for upgrading PNlib for Modelica 4.0.0?

**Comment by phannebohm** [comment]
Thanks for catching this. In the meantime you can easily convert PNlib yourself using [conversion scripts](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html?highlight=conversion#convert-libraries-using-conversion-scripts). Unfortunately there are some formatting issues with the resulting Modelica code. I'm currently cleaning up the library for a new release which should be coming very soon.

**Comment by phannebohm** [comment]
[PNlib v3.0.0 (2024-02-13)](https://github.com/AMIT-HSBI/PNlib/releases/tag/v3.0.0) is out now! :tada:
